server:
  port: 8002
spring:
  #数据源
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lss0555?serverTimezone=UTC
    username: root
    password: 888888
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  redis:
    host: 194.0.11.50
  #    host: 192.168.153.133
    port: 6379
  #    password: 888888
    timeout: 10000
    pool:
        # 连接池中的最大空闲连接
       max-idle: 8
        # 连接池中的最小空闲连接
       min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
       max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-wait: -1

mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.example.server.model
  mapper-locations: classpath*:mapping/*.xml