server:
  port: 8001
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

  redis:
    host: 194.0.11.50
    port: 6379
    timeout: 10000
    pool:
      max-idle: 8
      min-idle: 10
      max-wait: -1